version: '3'

services:

  redis:
    image: redis
    container_name: $REDIS_HOST
    ports:
      - "$REDIS_PORT:6379"
    networks:
      - app-network
  
  app1:
    build: .
    container_name: app1
    restart: unless-stopped
    ports:
      - "4200:$SERVER_PORT"
    env_file: 
      - .env
    volumes:
      - .:/app
    networks:
      - app-network
    command: npx nodemon app.js
  
  # app2:
  #   build: .
  #   container_name: app2
  #   restart: unless-stopped
  #   ports:
  #     - "4201:$SERVER_PORT"
  #   env_file: 
  #     - .env
  #   volumes:
  #     - .:/app
  #   networks:
  #     - app-network
  #   command: npx nodemon app.js

networks:
  app-network:
    driver: bridge